export const LOAD_USERS_START = "LOAD_USERS_START";
export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS";
export const LOAD_USERS_ERROR = "LOAD_USERS_ERROR";

export const REGISTER_USER_START = "REGISTER_USER_START";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const SET_USER = "SET_USER";

export const GOOGLE_SIGNIN_START = "GOOGLE_SIGNIN_START";
export const GOOGLE_SIGNIN_SUCCESS = "GOOGLE_SIGNIN_SUCCESS";
export const GOOGLE_SIGNIN_ERROR = "GOOGLE_SIGNIN_ERROR";

export const FACEBOOK_SIGNIN_START = "FACEBOOK_SIGNIN_START";
export const FACEBOOK_SIGNIN_SUCCESS = "FACEBOOK_SIGNIN_SUCCESS";
export const FACEBOOK_SIGNIN_ERROR = "FACEBOOK_SIGNIN_ERROR";
